services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sopikeur
      MYSQL_USER: sopikeur
      MYSQL_PASSWORD: sopikeur
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: sopikeur
      PMA_PASSWORD: sopikeur
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
