spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sopikeur?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:sopikeur}
    password: ${SPRING_DATASOURCE_PASSWORD:sopikeur}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: ${APP_JWT_SECRET:98e811a7263b57336afc22944f78d650e8cc557d987c606199b1b8d30cf2e5ec699c6ce71b74d0d04dfa54039b0b1f2fbb945b6d0f4dcd1925343be287e63fa6}
  cors:
    allowed-origins:
      - "http://localhost:4200"
      - "http://127.0.0.1:4200"
      - "http://localhost:4201"
  turnstile:
    secret: ${APP_TURNSTILE_SECRET:}

logging:
  level:
    root: INFO
    sn.sopikeur: DEBUG
