spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  cors:
    allowed-origins:
      - "https://sopikeur.sn"
      - "https://www.sopikeur.sn"
      - "https://admin.sopikeur.sn"
      - "https://develop.sopikeur-front.pages.dev"
  turnstile:
    secret: ${APP_TURNSTILE_SECRET:}

logging:
  level:
    root: INFO
